### ISSUE TITLE
Unibios don't show start options in KOF 2003

### ISSUE THREAD

**Issue by richterdeveloper** [libretro/geolith-libretro#3] opened 2024-04-30 15:13 UTC
When start King of Fighters 2003 (kof2003.neo, NGM-2710 Export) with Unibios, the initial boot screen only show the "Neo Geo" logo without the setup options. This occurs with the MAME set and Darksoft set of the game. In MAME, Unibios show the options without problem.

**Comment by carmiker** [comment] 2024-05-05 14:12
This is a strange one, because on real hardware it just boots directly (I have an MV-1C with Unibios). The options are actually there, but the text is not visible, so it is probably the FIX layer not being mapped correctly. I'm not sure if the correct fix is to make it boot directly, or make the text show up. I'll dig deeper.

**Comment by SRC267** [comment] 2024-05-08 10:10
I wanted to test unibios v4.0, so I added it to the RetroArch System folder (unzipped) and loaded a game, went to the quick menu, core options and changed system type from AES to Universe BIOS.

After closing and exiting the app, I tried to open a game but it crashed, deleting the geolith.opt file from the RetroArch config folder, reset the core. not sure what went wrong. Just thought I'd share that. Maybe I need to leave the bios zipped?

**Comment by carmiker** [comment] 2024-05-09 14:10
@SRC267 unibios 4.0 is included in aes.zip and neogeo.zip already. In this core, the one included in neogeo.zip is used, so I think the crash might be unrelated to what files you added to the system directory. I'll try to reproduce this problem.

**Comment by SRC267** [comment] 2024-05-09 19:31
I did this on android, and may have had both zipped and unzipped (in the folder) both in the System folder. Haven't tried it on PC.

**Comment by richterdeveloper** [comment] 2024-05-09 19:57
In addition, with the kof2003h romset, the game boots with the full options (I assume this romset is the home AES version). This issue only occurs with kof2003 romset (the MVS export).

**Comment by carmiker** [comment] 2024-05-12 16:33
I am taking a swing at this issue again, and have discovered some interesting points:
- If I force the backdrop to red and don't draw sprites, I see black boxes where the text should be. This means the FIX tile map is correct, but it is drawing black boxes because that is what it determines from reading the palette entries for the data returned for these tiles.
- If I use the kof2003h P ROMs with the kof2003 ROMs for everything else, the text shows up. This tells me it's something related to the game code itself.
- If I use Unibios 3.3, the text shows up.
- Logging palette RAM writes reveals some behavioural differences.

It is possible the issue is related to palette RAM, or the conversion from MAME to .neo format is not quite correct. I'm going to write my own conversion tool to find out.

**Comment by carmiker** [comment] 2024-05-14 21:01
Well, this was an interesting rabbit hole. It turns out that with the combination of Unibios 4.0 and kof2003, this behaviour will be exhibited if the correct bits are not set for the number of cartridge and coin slots.

**Closed by carmiker** 2024-05-14 21:01 UTC
